<div class="pull-left">
    <div class="btn-group">
        <a href="<?php echo $this->linkToRoute('admin-administrators-list');?>" class="btn btn-success"><i class="fa fa-arrow-circle-left"></i> <?php echo $this->translate('Back to list');?></a>
    </div>
</div>

<div class="clearfix"></div>

<br>

<div class="panel panel-default">
    <div class="panel-body">
        <form class="form" method="post">
<?php
if (isset($this->result)) {
    $status = (isset($this->result['errors']) ? 'danger' : 'success');
    echo Fennec\Library\Alerts::Create($status, $this->result['result']);
}
?>
            <div class="form-group">
                <label for="name"><?php echo $this->translate('Name');?></label>
                <input type="text" name="name" id="name" class="form-control" required value="<?php echo (isset($this->name) ? $this->name : null);?>">
            </div>
            
            <div class="form-group">
                <label for="username"><?php echo $this->translate('Username');?></label>
                <input type="text" name="username" id="username" class="form-control" required value="<?php echo (isset($this->username) ? $this->username : null);?>">
            </div>
            
            <div class="form-group">
                <label for="email"><?php echo $this->translate('Email');?></label>
                <input type="email" name="email" id="email" class="form-control" required value="<?php echo (isset($this->email) ? $this->email : null);?>">
            </div>
            
            <div class="form-group">
                <label for="password"><?php echo $this->translate('Password');?></label>
                <input type="password" name="password" id="password" class="form-control" required>
            </div>
            
            <div class="form-group">
                <button type="submit" class="btn btn-success"><?php echo $this->translate('Save');?></button>
            </div>
        </form>
    </div>
</div>