<div class="pull-left">
    <div class="btn-group">
        <a href="<?php echo $this->linkToRoute('admin-administrators-list');?>" class="btn btn-success"><i class="fa fa-arrow-circle-left"></i> Back to list</a>
    </div>
</div>

<div class="clearfix"></div>

<br>

<div class="panel panel-default">
    <div class="panel-body">
        <p><b>Name:</b> <?php echo $this->profile->getName();?></p>
        <p><b>Username:</b> <?php echo $this->profile->getUsername();?></p>
<?php
if ($this->profile->getEmail()) {
?>
        <p><b>Email:</b> <?php echo $this->profile->getEmail();?></p>
<?php
}
?>
        
    </div>
</div>