<!DOCTYPE html>
<html>
<head>
<link href="/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<script src="/assets/js/jquery-2.1.4.min.js" type="text/javascript"></script>
<script src="/assets/js/bootstrap.min.js" type="text/javascript"></script>
<meta charset="utf-8">
<title>Fennec CMS</title>
</head>
<body>

<div class="container">

    <header>
        <div class="well">
            <h1 class="text-center">Welcome</h1>
        </div>
    </header>

<?php
$this->loadView($this->view);
?>
</div>
</body>
</html>