    <div class="content-login">
      <div class="row">
        <div class="col-xs-4"></div>
        <div class="col-xs-4">
<?php
if (isset($this->errors)){
    echo '<div class="alert alert-danger">';
    foreach ($this->errors as $errorMessage) {
        echo $errorMessage . '<br>';
    }
    echo '</div>';
}
?>
          <div class="well">
            <form method="post">
              <div class="form-group">
                <label for="username"><?php echo $this->translate('Username');?></label><br>
                <input type="text" name="username" id="username" class="form-control">
              </div>
              
              <div class="form-group">
                <label for="password"><?php echo $this->translate('Password');?></label><br>
                <input type="password" name="password" id="password" class="form-control">
              </div>
              
              <div class="form-group">
                <button type="submit" class="btn btn-info btn-block">Login</button> 
              </div>
            </form>
          </div>
        </div>
        <div class="col-xs-4"></div>
      </div>
    </div>
    