<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Fennec CMS</title>
<meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
<link href="/internal/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="/internal/plugins/fontawesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);" type="text/css">
<link href="/internal/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
<link href="/internal/dist/css/skins/skin-blue.min.css" rel="stylesheet" type="text/css" />
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
      <a href="index2.html" class="logo">
        <span class="logo-mini">
          <img src="/internal/dist/img/fennec/logo-blue.png" style="height:32px; width:32px;">
        </span>
        <span class="logo-lg">
          <b><img src="/internal/dist/img/fennec/logo-blue.png" style="height:32px; width:32px;"> Fennec</b>
        </span>
      </a>

      <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
          <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src="/internal/dist/img/fennec/logo-blue.png" class="user-image" alt="User Image" />
                <span class="hidden-xs">Jack The Fox</span>
              </a>
              <ul class="dropdown-menu">
                <li class="user-header">
                  <img src="/internal/dist/img/fennec/logo-blue.png" class="img-circle" alt="User Image" />
                  <p>
                   Jack The Fox <small>Administrator since Jun. 2015</small>
                  </p>
                </li>

                <li class="user-footer">
                  <div class="pull-left">
                    <a href="#" class="btn btn-default btn-flat">Profile</a>
                  </div>
                  <div class="pull-right">
                    <a href="#" class="btn btn-default btn-flat">Sign out</a>
                  </div>
                </li>
              </ul>
            </li>
            <li>
              <a href="#" data-toggle="control-sidebar">
                <i class="fa fa-gears"></i>
              </a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <aside class="main-sidebar">

      <section class="sidebar">
        <ul class="sidebar-menu">
          <li class="header">MODULES</li>
        </ul>
      </section>
    </aside>

    <div class="content-wrapper">
      <section class="content-header">
        <h1>
          Dashboard <small>Your favorite modules</small>
        </h1>
      </section>

      <section class="content"></section>
    </div>

    <footer class="main-footer">
      <div class="pull-right hidden-xs text-gray">b0.1</div>
      <strong>&nbsp;</strong>
    </footer>
  </div>

  <script src="/internal/plugins/jQuery/jQuery-2.1.4.min.js"></script>
  <script src="/internal/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
  <script src="/internal/dist/js/app.min.js" type="text/javascript"></script>
</body>
</html>