<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Fennec CMS</title>
<meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
<link href="/internal/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="/internal/plugins/fontawesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);" type="text/css">
<link href="/internal/dist/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
<link href="/internal/dist/css/skins/skin-blue.min.css" rel="stylesheet" type="text/css" />
<link href="/internal/plugins/datetimepicker/bootstrap-datetimepicker.min.css" rel="stylesheet" type="text/css" />
<link href="/internal/plugins/summernote/summernote.css" rel="stylesheet" type="text/css" />
<link href="/internal/plugins/tagsinput/bootstrap-tagsinput.css" rel="stylesheet" type="text/css" />
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="skin-blue sidebar-mini">
  <div class="wrapper">
    <header class="main-header">
      <a href="index2.html" class="logo">
        <span class="logo-mini">
          <img src="/internal/dist/img/fennec/logo-blue.png" style="height:32px; width:32px;">
        </span>
        <span class="logo-lg">
          <b><img src="/internal/dist/img/fennec/logo-blue.png" style="height:32px; width:32px;"> Fennec</b>
        </span>
      </a>

      <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
          <span class="sr-only">Toggle navigation</span>
        </a>
        <div class="navbar-custom-menu">
          <ul class="nav navbar-nav">
            <li class="dropdown user user-menu">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <img src="/internal/dist/img/fennec/logo-blue.png" class="user-image" alt="User Image" />
                <span class="hidden-xs">Jack The Fox</span>
              </a>
              <ul class="dropdown-menu">
                <li class="user-header">
                  <img src="/internal/dist/img/fennec/logo-blue.png" class="img-circle" alt="User Image" />
                  <p>
                   <?php echo $_SESSION['fennecAdmin']->getName();?> <small>Administrator since <?php echo $_SESSION['fennecAdmin']->getSince()->format('M. Y');?></small>
                  </p>
                </li>

                <li class="user-footer">
                  <div class="pull-left">
                    <a href="<?php echo $this->linkToRoute('admin-administrators-profile', array($_SESSION['fennecAdmin']->getId()));?>" class="btn btn-default btn-flat">Profile</a>
                  </div>
                  <div class="pull-right">
                    <a href="<?php echo $this->linkToRoute('admin-logout');?>" class="btn btn-default btn-flat">Sign out</a>
                  </div>
                </li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <aside class="main-sidebar">

      <section class="sidebar">
        <ul class="sidebar-menu">
          <li class="header">MODULES</li>
<?php
foreach ($this->menu as $title => $menu) {
    $class = array();
    $isMultilevel = (isset($menu['subitems']) && count($menu['subitems']));
    $class[] = ($isMultilevel ? 'treeview' : '');
    $controller = addslashes(Fennec\Library\Router::$routes[$menu['route']]['controller']);

    if (preg_match("/$controller/", get_class($this))) {
        $class[] = 'active';
    }
    $class = implode(" ", $class);
?>
            <li<?php echo $class ? " class=\"$class\"" : null;?>>
                <a href="<?php echo Fennec\Library\Router::$routes[$menu['route']]['original-route'];?>"><?php echo $title;?></a>
<?php
    if ($isMultilevel) {
?>
                <ul class="treeview-menu">
<?php
        foreach($menu['subitems'] as $name => $subRoute) {
?>
                    <li>
                        <a href="<?php echo Fennec\Library\Router::$routes[$subRoute]['original-route'];?>">
                            <span><?php echo $name;?></span>
                        </a>
                    </li>
<?php
        }
?>
                </ul>
<?php
    }
?>
            </li>
<?php
}
?>
        </ul>



        <!-- <ul class="sidebar-menu">
            <li class="active"><a href="#"><i class='fa fa-link'></i> <span>Link</span></a></li>
            <li><a href="#"><i class='fa fa-link'></i> <span>Another Link</span></a></li>
            <li class="treeview">
              <a href="#"><i class='fa fa-link'></i> <span>Multilevel</span> <i class="fa fa-angle-left pull-right"></i></a>
              <ul class="treeview-menu">
                <li><a href="#">Link in level 2</a></li>
                <li><a href="#">Link in level 2</a></li>
              </ul>
            </li>
          </ul>

          -->
      </section>
    </aside>

    <div class="content-wrapper">
<?php
if ($this->moduleInfo) {
?>
      <section class="content-header">
        <h1>
          <?php echo $this->moduleInfo['title'];?>
          <?php echo (isset($this->moduleInfo['subtitle']) ? "<small>{$this->moduleInfo['subtitle']}</small>" : null);?>
        </h1>
      </section>
<?php
}
?>

      <section class="content">
<?php
$this->loadView($this->view);
?>
      </section>
    </div>

    <footer class="main-footer">
      <div class="pull-right hidden-xs text-gray">b0.1</div>
      <strong>&nbsp;</strong>
    </footer>
  </div>

  <script src="/internal/plugins/jQuery/jQuery-2.1.4.min.js"></script>
  <script src="/internal/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
  <script src="/internal/plugins/moment/moment.min.js" type="text/javascript"></script>
  <script src="/internal/plugins/datetimepicker/bootstrap-datetimepicker.min.js"></script>
  <script src="/internal/plugins/summernote/summernote.min.js" type="text/javascript"></script>
  <script src="/internal/plugins/tagsinput/bootstrap-tagsinput.min.js" type="text/javascript"></script>
  <script src="/internal/dist/js/app.min.js" type="text/javascript"></script>
  <script src="/internal/dist/js/fennec.js" type="text/javascript"></script>
</body>
</html>