<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Login :: Fennec CMS</title>
<meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
<link href="/internal/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="/internal/plugins/fontawesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);" type="text/css">
<link href="/internal/dist/css/AdminLTE.css" rel="stylesheet" type="text/css" />
<link href="/internal/dist/css/skins/skin-blue.min.css" rel="stylesheet" type="text/css" />
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="skin-blue sidebar-mini">
  <div class="wrapper">
<?php
$this->loadView($this->view);
?>
  </div>

  <script src="/internal/plugins/jQuery/jQuery-2.1.4.min.js"></script>
  <script src="/internal/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
  <script src="/internal/dist/js/app.min.js" type="text/javascript"></script>
</body>
</html>
